apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  labels:
    app: devops-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      serviceAccountName: devops-app-sa
      containers:
      - name: devops-app
        image: node:18-alpine
        imagePullPolicy: IfNotPresent
        workingDir: /app
        command: ["sh"]
        args:
        - -c
        - |
          # Устанавливаем git и клонируем репозиторий
          apk add --no-cache git
          git clone https://github.com/sttewiee/bestdevops.git /app
          cd /app
          # Устанавливаем зависимости и запускаем приложение
          npm install
          npm start &
          # Держим контейнер живым
          tail -f /dev/null
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 5
