apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  labels:
    app: devops-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      serviceAccountName: devops-app-sa
      # Убираем nodeSelector - разрешаем запуск на любых узлах
      # nodeSelector:
      #   node-role.kubernetes.io/control-plane: ""
      # Убираем сложный initContainer - будем использовать простой подход
      containers:
      - name: devops-app
        image: nginx:alpine  # ← Используем простой nginx для тестирования
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        # Убираем переменные окружения для nginx
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      # Убираем volumes - они больше не нужны
