apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  labels:
    app: devops-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      serviceAccountName: devops-app-sa
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""  # Запускаем на control plane узле
      # Убираем сложный initContainer - будем использовать простой подход
      containers:
      - name: devops-app
        image: node:18-alpine  # ← Используем готовый образ Node.js
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        command: ["sh"]
        args:
        - -c
        - |
          # Устанавливаем зависимости и запускаем приложение
          apk add --no-cache git
          git clone https://github.com/sttewiee/bestdevops.git
          cd bestdevops
          npm install
          npm start
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: devops-app-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: devops-app-config
              key: PORT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: devops-app-config
              key: LOG_LEVEL
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      # Убираем volumes - они больше не нужны
