apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-app-sa
  namespace: devops-lab
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devops-app-reader
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "services", "namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devops-app-binding
subjects:
- kind: ServiceAccount
  name: devops-app-sa
  namespace: devops-lab
roleRef:
  kind: ClusterRole
  name: devops-app-reader
  apiGroup: rbac.authorization.k8s.io
