name: Deploy to Kubernetes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build Docker image
      run: |
        docker build -t devops-app:latest .
        
    - name: Deploy to Kubernetes
      run: |
        # Здесь будут команды деплоя в K8s
        echo "Deploying to Kubernetes cluster..."
